version: "3.7"
services:
  url-shortener-server:
    restart: always
    container_name: json-hub
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build:
      context: ./
    image: json-hub
    ports:
      - "5000:5000"
